package rules

import com.my.drools.entity.Order
//每当规则有变动的时候，我们只需要修改规则⽂件，然后重新加载即可⽣效

//规则1：100元以下, 不加分
rule "score_1"

when
$s : Order(amout <= 100)
then
$s.setScore(0);
System.out.println("成功匹配到规则1：100元以下, 不加分 ");
end

//规则2：100元-500元 加100分
rule "score_2"
when
$s : Order(amout > 100 && amout <= 500)
then
$s.setScore(100);
System.out.println("成功匹配到规则2：100元-500元 加100分 ");
end

//规则3：500元-1000元 加500分
rule "score_3"
when
$s : Order(amout > 500 && amout <= 1000)
then
$s.setScore(500);
System.out.println("成功匹配到规则3：500元-1000元 加500分 ");
end

//规则4：1000元 以上 加1000分
rule "score_4"
when
$s : Order(amout > 1000)
then
$s.setScore(1000);
System.out.println("成功匹配到规则4：1000元 以上 加1000分 ");
end